project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - schedule.qmd
    - 01_command_shells.qmd

execute: 
  freeze: auto

website:
  title: "CS/DS 549 Spark! Machine Learning Practicum"
  back-to-top-navigation: true
  favicon: "assets/images/spark-logo.png"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home -- Syllabus
      - href: schedule.qmd
      - section: "Assignments"
        contents:
          - href: 01_command_shells.qmd
            text: 01 -- Command Shells

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: false



