project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - schedule.qmd
    - 01_command_shells.qmd
    - 02_python_environments.qmd

execute: 
  freeze: auto

website:
  title: "CS/DS 549 Spark! Machine Learning Practicum"
  back-to-top-navigation: true
  favicon: "assets/images/spark-logo.png"
  page-footer: "CS/DS 549 Spark! Machine Learning Practicum"
  navbar:
    background: "primary"
    tools:
    - icon: github
      menu: 
      - text: Source Code
        href: https://github.com/trgardos/ml-549-fa24
      - text: Report a Bug
        href: https://github.com/trgardos/ml-549-fa24/issues
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home -- Syllabus
      - href: schedule.qmd
      - section: "Assignments"
        contents:
          - href: 01_command_shells.qmd
            text: 01 -- Command Shells
          - href: 02_python_environments.qmd
            text: 02 -- Python Environments

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: false
