project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - schedule.qmd
    - projects.qmd
    - 01_command_shells.qmd
    - 02_python_environments.qmd
    - 03_git_github.qmd
    - 04_scc.qmd
    - 07_scc_cont.qmd
    - 08_scc_batch_computing.qmd
    - 10-pytorch-01.qmd
    - 12-pytorch-02-dataloaders.qmd
    - 13-pytorch-03-model-def.qmd
    - 14-pytorch-04-autograd.qmd
    - 15-pytorch-05-training.qmd
execute: 
  freeze: auto
  # cache: true

website:
  title: "CS/DS 549 Spark! Machine Learning Practicum"
  back-to-top-navigation: true
  favicon: "assets/images/spark-logo.png"
  page-footer: "CS/DS 549 Spark! Machine Learning Practicum"
  navbar:
    background: "primary"
    tools:
    - icon: github
      menu: 
      - text: Source Code
        href: https://github.com/trgardos/ml-549-fa24
      - text: Report a Bug
        href: https://github.com/trgardos/ml-549-fa24/issues
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home -- Syllabus
      - href: schedule.qmd
      - href: projects.qmd
      - section: "Notes"
        contents:
          - href: 01_command_shells.qmd
            text: 01 -- Command Shells
          - href: 02_python_environments.qmd
            text: 02 -- Python Environments
          - href: 03_git_github.qmd
            text: 03 -- Git and GitHub
          - href: 04_scc.qmd
            text: 04 -- Shared Computing Cluster
          - href: 07_scc_cont.qmd
            text: 07 -- SCC Continued
          - href: 08_scc_batch_computing.qmd
            text: 08 -- SCC Batch Computing
          - href: 10-pytorch-01.qmd
            text: 10 -- PyTorch 01 - Intro and Tensors
          - href: 12-pytorch-02-dataloaders.qmd
            text: 12 -- PyTorch 02 - Dataloaders and Transforms
          - href: 13-pytorch-03-model-def.qmd
            text: 13 -- PyTorch 03 - Model Definition
          - href: 14-pytorch-04-autograd.qmd
            text: 14 -- PyTorch 04 - Autograd
          - href: 15-pytorch-05-training.qmd
            text: 15 -- PyTorch 05 - Training and Evaluation

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 5
    code-fold: false
